/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddHrProfileModal: typeof import('./src/components/modals/AddHrProfileModal.vue')['default']
    DialogComponent: typeof import('./src/components/modals/DialogComponent.vue')['default']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ForgotPasswordModal: typeof import('./src/components/modals/ForgotPasswordModal.vue')['default']
    InviteAdUsersModal: typeof import('./src/components/modals/InviteAdUsersModal.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    ModalComponent: typeof import('./src/components/modals/ModalComponent.vue')['default']
    ResumePreviewModal: typeof import('./src/components/modals/ResumePreviewModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TenantProfileModal: typeof import('./src/components/modals/TenantProfileModal.vue')['default']
    UserPrivilegeModal: typeof import('./src/components/modals/UserPrivilegeModal.vue')['default']
    UserProfileModal: typeof import('./src/components/modals/UserProfileModal.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
