/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BPagination: typeof import('bootstrap-vue-next')['BPagination']
    DialogComponent: typeof import('./src/components/modals/DialogComponent.vue')['default']
    LeftMenu: typeof import('./src/components/layoutComponents/LeftMenu.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    NavBar: typeof import('./src/components/layoutComponents/NavBar.vue')['default']
    ResumePreviewModal: typeof import('./src/components/modals/ResumePreviewModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
